GCC=g++ -std=c++11

all:
	$(GCC) 1-16-可调用对象的使用示例.cpp -o 1-16.elf
	$(GCC) 1-17-std::function的基本用法.cpp -o 1-17.elf
	$(GCC) 1-18-std::function作为回调函数的示例.cpp -o 1-18.elf
	$(GCC) 1-19-std::function作为函数入参的示例.cpp -o 1-19.elf
	$(GCC) 1-20-std::bind的基本用法.cpp -o 1-20.elf

clean:
	rm *.elf -f
