GCC=g++ -std=c++11

all:
	$(GCC) getinfo.cpp -o getinfo.elf
	$(GCC) limits.cpp -o limits.elf
	$(GCC) hexoct.cpp -o hexoct.elf
	$(GCC) hexoct2.cpp -o hexoct2.elf
	$(GCC) chartype.cpp -o chartype.elf
	$(GCC) morechar.cpp -o morechar.elf

clean:
	rm *.elf -f
