GCC=g++ -std=c++11
FLAG=-fno-elide-constructors

all:
	$(GCC) 2-类型判断的type_traits.cpp -o 2-类型判断的type_traits.elf
	$(GCC) 3-判断两个类型之间的关系traits.cpp -o 3-判断两个类型之间的关系traits.elf
	$(GCC) 4-类型的转换traits.cpp -o 4-类型的转换traits.elf

clean:
	rm *.elf -f
